# Generated by Django 4.0 on 2023-09-30 15:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_category_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 30, 15, 17, 28, 126889, tzinfo=utc)),
        ),
    ]
